language: python
python:
    - 3.10.7
before_install:
    pip install coverage pytest pytest-cov dicttoxml validate_email
script:
    - python -m py_compile logXchecker.py
    - python -m py_compile edi.py
    - python -m py_compile rules.py
    - python -m py_compile test_edi.py
    - python -m py_compile test_rules.py
    - python -m py_compile test_parser.py
    - pytest --cov --cov-fail-under=87
