language: python
python:
    - 3.6.1
before_install:
    pip install nose coverage
script:
    - python -m py_compile logXchecker.py
    - python -m py_compile edi.py
    - python -m py_compile rules.py
    - python -m py_compile test_edi.py
    - python -m py_compile test_rules.py
    - python -m py_compile test_parser.py
    - nosetests -v --with-coverage --cover-erase --cover-html --cover-package=. --cover-min-percentage=92
